# Generated by Django 2.0.4 on 2018-06-18 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('sale', 'Sale'), ('sample', 'Sample'), ('spoil', 'Spoil'), ('return', 'Return')], max_length=32)),
                ('retailer', models.CharField(choices=[('amazon', 'Amazon'), ('website', 'Website')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('amazon', 'Amazon'), ('PayPal', 'PayPal')], max_length=32)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
