# Generated by Django 2.0.4 on 2018-06-01 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('bag_colour', models.CharField(choices=[('65428A', 'Pantone Medium Purple U'), ('FFFFFF', 'White')], max_length=32)),
                ('bag_material', models.CharField(max_length=32)),
                ('label_colour', models.CharField(choices=[('65428A', 'Pantone Medium Purple U'), ('FFFFFF', 'White')], max_length=30)),
                ('label_material', models.CharField(max_length=32)),
                ('label_text', models.CharField(max_length=16)),
                ('drawstring_colour', models.CharField(choices=[('65428A', 'Pantone Medium Purple U'), ('FFFFFF', 'White')], max_length=32)),
                ('drawstring_material', models.CharField(max_length=32)),
                ('units', models.PositiveIntegerField()),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='BaggySoap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.PositiveIntegerField()),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Bag')),
            ],
        ),
        migrations.CreateModel(
            name='Soap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('fragrance', models.CharField(max_length=64)),
                ('colour', models.CharField(max_length=64)),
                ('units', models.PositiveIntegerField()),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.AddField(
            model_name='baggysoap',
            name='soap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Soap'),
        ),
    ]
