# Generated by Django 2.0.4 on 2018-06-20 20:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('units', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='BaggySoap',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogue.Product')),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('image', models.ImageField(blank=True, null=True, upload_to='baggy_soaps')),
            ],
            options={
                'verbose_name': 'Baggy Soap',
            },
            bases=('catalogue.product',),
        ),
        migrations.CreateModel(
            name='SoapBag',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogue.Product')),
                ('bag_colour', models.CharField(choices=[('65428A', 'Pantone Medium Purple U'), ('FFFFFF', 'White')], max_length=32)),
                ('bag_material', models.CharField(max_length=32)),
                ('label_colour', models.CharField(choices=[('65428A', 'Pantone Medium Purple U'), ('FFFFFF', 'White')], max_length=30)),
                ('label_material', models.CharField(max_length=32)),
                ('label_text', models.CharField(max_length=16)),
                ('drawstring_colour', models.CharField(choices=[('65428A', 'Pantone Medium Purple U'), ('FFFFFF', 'White')], max_length=32)),
                ('drawstring_material', models.CharField(max_length=32)),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Cost per bag, including shipping', max_digits=4)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
            ],
            options={
                'verbose_name': 'Bag',
            },
            bases=('catalogue.product',),
        ),
        migrations.CreateModel(
            name='SoapBar',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogue.Product')),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('image', models.ImageField(blank=True, null=True, upload_to='soap_bars')),
            ],
            options={
                'verbose_name': 'Soap Bar',
            },
            bases=('catalogue.product',),
        ),
        migrations.CreateModel(
            name='SoapLoaf',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogue.Product')),
                ('fragrance', models.CharField(max_length=64)),
                ('colour', models.CharField(max_length=64)),
                ('ingredients', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True)),
                ('wholesale_link', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sls_free', models.BooleanField(default=False, verbose_name='SLS Free')),
                ('parabens_free', models.BooleanField(default=False, verbose_name='Parabens Free')),
                ('palm_oil_free', models.BooleanField(default=False, verbose_name='Palm Oil Free')),
                ('made_in_uk', models.BooleanField(default=False, verbose_name='Made in the UK')),
                ('contains_essential_oils', models.BooleanField(default=False, verbose_name='Contains Essential Oils')),
                ('vegan_friendly', models.BooleanField(default=False, verbose_name='Vegan Friendly')),
                ('organic', models.BooleanField(default=False, verbose_name='Organic')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Weight (in kg)')),
                ('bars_per_loaf', models.PositiveIntegerField()),
                ('list_price', models.DecimalField(decimal_places=2, help_text='Cost per loaf, excluding shipping', max_digits=4)),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Cost per loaf, including shipping', max_digits=4)),
            ],
            options={
                'verbose_name': 'Soap Loaf',
            },
            bases=('catalogue.product',),
        ),
        migrations.AddField(
            model_name='soapbar',
            name='loaf',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalogue.SoapLoaf'),
        ),
        migrations.AddField(
            model_name='baggysoap',
            name='bag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.SoapBag'),
        ),
        migrations.AddField(
            model_name='baggysoap',
            name='soap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.SoapBar'),
        ),
        migrations.AlterUniqueTogether(
            name='baggysoap',
            unique_together={('bag', 'soap')},
        ),
    ]
