# Generated by Django 2.0.4 on 2018-06-01 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baggysoap',
            options={'verbose_name': 'Baggy Soap'},
        ),
    ]
