# Generated by Django 2.0.4 on 2018-06-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baggysoap',
            name='image',
        ),
        migrations.RemoveField(
            model_name='soapbar',
            name='image',
        ),
        migrations.AddField(
            model_name='baggysoap',
            name='image_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='soapbar',
            name='image_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
