# Generated by Django 2.0.4 on 2018-06-05 14:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_add_verbose_name_to_baggy_soap'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoapBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.PositiveIntegerField()),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'verbose_name': 'Soap Bar',
            },
        ),
        migrations.CreateModel(
            name='SoapLoaf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('fragrance', models.CharField(max_length=64)),
                ('colour', models.CharField(max_length=64)),
                ('ingredients', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True)),
                ('weight', models.PositiveIntegerField(verbose_name='Weight (in kg)')),
                ('units', models.PositiveIntegerField()),
                ('bars_per_loaf', models.PositiveIntegerField()),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Cost per loaf, including shipping', max_digits=4)),
            ],
            options={
                'verbose_name': 'Soap Loaf',
            },
        ),
        migrations.AlterField(
            model_name='bag',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, help_text='Cost per bag, including shipping', max_digits=4),
        ),
        migrations.AlterField(
            model_name='baggysoap',
            name='soap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.SoapBar'),
        ),
        migrations.DeleteModel(
            name='Soap',
        ),
        migrations.AddField(
            model_name='soapbar',
            name='loaf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.SoapLoaf'),
        ),
    ]
