# Generated by Django 2.0.4 on 2018-06-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_create_soap_loaf_and_soap_bar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soaploaf',
            name='units',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='soaploaf',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Weight (in kg)'),
        ),
    ]
