# Generated by Django 2.0.4 on 2018-06-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_allow_decimals_in_loaf_weight_and_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='soaploaf',
            name='contains_essential_oils',
            field=models.BooleanField(default=False, verbose_name='Contains Essential Oils'),
        ),
        migrations.AddField(
            model_name='soaploaf',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='soaploaf',
            name='list_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost per loaf, excluding shipping', max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soaploaf',
            name='made_in_uk',
            field=models.BooleanField(default=False, verbose_name='Made in the UK'),
        ),
        migrations.AddField(
            model_name='soaploaf',
            name='organic',
            field=models.BooleanField(default=False, verbose_name='Organic'),
        ),
        migrations.AddField(
            model_name='soaploaf',
            name='palm_oil_free',
            field=models.BooleanField(default=False, verbose_name='Palm Oil Free'),
        ),
        migrations.AddField(
            model_name='soaploaf',
            name='parabens_free',
            field=models.BooleanField(default=False, verbose_name='Parabens Free'),
        ),
        migrations.AddField(
            model_name='soaploaf',
            name='sls_free',
            field=models.BooleanField(default=False, verbose_name='SLS Free'),
        ),
        migrations.AddField(
            model_name='soaploaf',
            name='vegan_friendly',
            field=models.BooleanField(default=False, verbose_name='Vegan Friendly'),
        ),
        migrations.AddField(
            model_name='soaploaf',
            name='wholesale_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
