# Generated by Django 2.0.4 on 2018-06-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_add_fields_to_soap_loaf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
