# Generated by Django 2.0.4 on 2018-06-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_set_bag_sell_price_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='baggysoap',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='baggy_soaps'),
        ),
        migrations.AddField(
            model_name='soapbar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='soap_bars'),
        ),
    ]
