# Generated by Django 2.0.4 on 2018-06-12 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_alter_loaf_to_be_unique_for_bar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='baggysoap',
            unique_together={('bag', 'soap')},
        ),
    ]
