# Generated by Django 2.0.4 on 2018-06-18 21:09

from django.db import migrations

from catalogue.models import create_product


def move_forwards(apps, schema_editor):
    Bag = apps.get_model("catalogue", "Bag")
    SoapBar = apps.get_model("catalogue", "SoapBar")
    BaggySoap = apps.get_model("catalogue", "BaggySoap")

    for bag in Bag.objects.order_by('id').iterator():
        create_product(bag)

    for soap in SoapBar.objects.order_by('id').iterator():
        create_product(soap)

    for baggy_soap in BaggySoap.objects.order_by('id').iterator():
        create_product(baggy_soap)


def move_backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_create_product_model')
    ]

    operations = [
        migrations.RunPython(move_forwards, move_backwards)
    ]
